config/routes.rb
PMS::Application.routes.draw do
  devise_for :people

  resources :projects do
    resources :task_groups
  end

  resources :task_groups do
    resources :tasks
  end

  resources :tasks do
    post 'assignment'
  end

  resources :connections

  resources :people do
    resources :tasks do
      get 'release'
    end
  end

  root :to => "projects#index"

end

app/models/connection.rb
class Connection < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :tasks, :through => :connection
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :title, :presence => true
  validates :deadline, :presence => true
  has_many :task_groups, :dependent => :destroy
  attr_accessible :title, :status, :description, :deadline, :budget

end

# == Schema Information
#
# Table name: projects
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  description :text
#  deadline    :datetime
#  status      :string(255)
#  budget      :integer
#  created_at  :datetime
#  updated_at  :datetime
#

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :task_group
  has_many :people, :through => :connection
  validates :name, :presence => true

  def set_name
    self.name
  end
end

# == Schema Information
#
# Table name: tasks
#
#  id            :integer         not null, primary key
#  name          :string(255)
#  duration      :integer
#  task_group_id :integer
#  status        :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#

app/models/task_category.rb
class TaskCategory < ActiveRecord::Base
end

app/models/task_group.rb
class TaskGroup < ActiveRecord::Base
  belongs_to :project
  has_many :tasks, :dependent => :destroy
end

# == Schema Information
#
# Table name: task_groups
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  duration   :integer
#  created_at :datetime
#  updated_at :datetime
#  project_id :integer
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def show
    @person = Person.find(params[:id])
    @connections = Connection.find(:all, :order => 'id DESC', :conditions => [ 'person_id = ?', @person.id])
  end

  def index
    @people = Person.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_person!

  def index
    @projects= Project.all
  end

  def create
    @project=Project.new(params[:project])
    if @project.save
      redirect_to projects_path,:notice =>'New Project added'
    else
      render :action => "new", :alert => 'Project couldnot be added. Try again'
    end
  end

  def new
    @project=Project.new
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
       redirect_to projects_path, :notice => "Project Deleted Successfully"
    else
       redirect_to projects_path, :alert => "Project Deletion Failed!!"
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to(projects_path, :notice => "Project Updated Successfully")
    else
      render :action => "edit", :alert => "Project Update Failure!!"
    end
  end

  def show
    @project = Project.find(params[:id])
    @task_groups= @project.task_groups
  end

  def edit
    @project = Project.find(params[:id])
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

end

app/controllers/task_groups_controller.rb
class TaskGroupsController < ApplicationController
  def index
    @project = Project.find(params[:project_id])
    @task_groups = @project.task_groups.all
  end

  def show
      @task_group=TaskGroup.find(params[:id])
      @project = @task_group.project
      @tasks= @task_group.tasks
      @people= Person.all
  end

  def create
    @project=Project.find(params[:project_id])
    @task_group = @project.task_groups.new(params[:task_group])
    @task_group.save
    if @task_group.save
       redirect_to project_path(@project), :notice =>'New TaskGroup added'
     else
       render :action => "new", :alert => 'TaskGroup couldnot be added. Try again'
     end
  end

  def new
    @project = Project.find(params[:project_id])
    @task_group = @project.task_groups.new
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @task_group = TaskGroup.find(params[:id])
    @tasks= @task_group.tasks.all
  end

  def create
    @task_group = TaskGroup.find(params[:task_group_id])
    @task_group =
    if @task = @task_group.tasks.create(params[:task])
      redirect_to task_group_path(@task_group)
    else
      render :action => "new", :alert => 'Task couldnot be added. Try again'
    end
  end

  def new
    @task_group = TaskGroup.find(params[:task_group_id])
    @task = @task_group.tasks.new
  end

  def edit
    @task = Task.find(params[:id])
    @task_group = @task.task_group
  end

  def show
    @people = Person.all
    @task = Task.find(params[:id])
    @task_group= @task.task_group
    @connections = Connection.where(:task_id => @task.id)
  end

  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(params[:task])
        redirect_to task_path(@task), :notice => "Task Updated Successfully"
    else
        redirect_to :action => "edit", :alert => "Task Update Failed!!"
    end
  end

  def assignment
    @task = Task.find(params[:task_id])
    @task_group = @task.task_group
    @person = Person.find(params[:people])
    Connection.find_or_create_by_task_id_and_person_id(:task_id => @task.id, :person_id => @person.id)
    redirect_to task_group_task_path(@task_group, @task), :notice => @task.name + " with id " + @task.id.to_s + " is now assigned to " + @person.name
  end

   def release
    @task = Task.find(params[:task_id])
    @person = Person.find(params[:person_id])
    Connection.delete_all(:task_id => @task.id, :person_id => @person.id)
    flash[:alert]= "#{@person.name} has been released form Task: #{@task.name}"
    redirect_to person_path(@person)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def id2task(id)
    @task = Task.find(:all, :conditions => ['id = ?', id])
  end

  def rls(task, person)
    #Connection.delete_all(:task_id => task.id, :person_id => person.id)
    #flash[:alert]= "#{person.name} has been released form Task: #{task.name}"
  end

  def date_diff_in_days(date)
    difference = (date - Date.today).to_i
    if difference > -1
      difference = "#{difference} days remaining"
    else
      difference = "Expired"
    end
    difference
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def project_status(project)
    @task_groups = project.task_groups
    @bool = true
    @count = 0
    @complete_count = 0

    @task_groups.each do |task_group|
      task_group.tasks.each do |task|
        @count += 1
        if task.status != "Finished"
          @bool = false

      else
        @complete_count += 1
      end
      end
    end
   if @count != 0
     @percent_complete = (@complete_count/@count.to_f) * 100
   else
     @percent_complete = 0
   end
   @percent_complete
  end
end

app/helpers/task_groups_helper.rb
module TaskGroupsHelper
		
end

app/helpers/tasks_helper.rb
module TasksHelper

  def connected_people(connections)
    @person = Array.new
    connections.each do |obj|
      @person.push(Person.find(obj.person_id))
    end
    @person
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PMS</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery.min','jquery-ui.min','rails','application' %>
  <%= csrf_meta_tag %>
</head>
<body>
<h1>
<%= link_to "Project Management System", projects_path %> </h1>
<%= render :partial => "shared/link" %>
<hr />
<div id="notice">
  <%= notice %>
</div>
<div id="alert">
  <%= alert %>
</div>
<div id="yield">
  <%= yield %>
</div>
</body>
</html>

app/views/people/index.html.erb
<% @people.each do |person| %>
  <%= person.name %>
  <%= person.email %>
<br />
<% end %>

app/views/people/show.html.erb
<%= "#{@person.name} is assigned to following Tasks:" %> <br />
<% @connections.each do |conn| %>
  <% @tasks = id2task(conn.task_id) %>
  <% @tasks.each do |task| %>
    <%= link_to "#{task.name}", task_path(task.id) %>
    <%= link_to "Release", person_task_release_path(@person, task)  %> <br />
  <% end %>
<% end %>

app/views/projects/_form.html.erb
<%= semantic_form_for @project do |form| %>
  <%= form.inputs do %>
  <%= form.input :title %>
  <%= form.input :description, :as => :text %>
  <%= form.input :status %>
  <%= form.input :budget %>
  <%= form.input :deadline, :as => :string %>
  <%= form.buttons %>
  <%= form.semantic_errors :alert %>
  <% end %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>
<%= render "form" %>

app/views/projects/index.html.erb
<h2>Projects List</h2> <%= link_to "Create New Project", new_project_path %>
<div id="projects_list">
<ul>
  <% @projects.each do |proj| %>
    <li class="project_list">
    <% @val= project_status(proj) %>
    <h3><%= link_to "#{proj.title}", project_path(proj) %></h3>
    Status: <%= "#{@val.round(2)}% complete" %> |
    Created at: <%= proj.created_at.to_s(:project_date) %> |
    Deadline: <%= proj.deadline %> |
    <%= date_diff_in_days(proj.deadline) %> <br />
    <%= link_to "Edit", edit_project_path(proj) %>
    <%= link_to "Delete", project_path(proj), :confirm => "Are you sure you want to delete?", :method => :delete %>
    </li> <br />
  <% end %>
</ul>
</div>

app/views/projects/new.html.erb
<h1>Add new Project</h1>
<%= render 'form' %>

app/views/projects/show.html.erb
<div id="project_show">
<h1>Project: <%= @project.title %> </h1>
<h3>
<% @val= project_status(@project) %>
Status: <%= "#{@val.round(2)}% complete" %> <br />
Description: <%= @project.description %> <br />
Created At: <%= @project.created_at.to_s(:project_date) %> <br />
Deadline: <%= @project.deadline %> <br />
</h3>

<h2>Available Task Groups</h2>
<%= render "/task_groups/task_groups" %>
</div>

app/views/shared/_link.html.erb
<% if person_signed_in? %>
  <%= "Welcome #{current_person.name}!" %> |

  <%= "You last signed in at #{time_ago_in_words(current_person.last_sign_in_at)} ago from #{current_person.last_sign_in_ip}" %>

  <%= link_to "SignOut", destroy_person_session_path %>
<% else %>
  <%= link_to "SignIn", new_person_session_path %>
<% end %>

app/views/task_groups/_form.html.erb
<% semantic_form_for ([@project, @project.task_groups.build]) do |form| %>
  <% form.inputs do %>
  <%= form.input :name %>
  <%= form.input :duration %>
  <%= form.buttons %>
  <% end %>
<% end %>

app/views/task_groups/_member_select.html.erb
<% form_tag (task_assignment_path(@task)) do %>
<%= select_tag "people", options_from_collection_for_select(@people, "id", "name") %>
<%= submit_tag "Assign" %>
<% end %>

app/views/task_groups/_task_groups.html.erb
<%= link_to "Create New TaskGroup", new_project_task_group_path(@project) %>
<div id="task_groups_list">
<ul>
  <% @task_groups.each do |taskgroup| %>
    <li>
    <%= link_to "#{taskgroup.name}", task_group_path(taskgroup) %>
    Duration: <%= taskgroup.duration %> Days
    </li>
  <% end %>
</ul>
</div>

app/views/task_groups/index.html.erb
<%= render "task_groups" %>

app/views/task_groups/new.html.erb
<h1>Add new TaskGroup</h1>
<%= render 'form' %>

app/views/task_groups/show.html.erb
<h1> <%= @project.title %> </h1>
<h3>TaskGroup: <%= @task_group.name %></h3>

<div class="create_task">
  <%= link_to "Create Tasks", new_task_group_task_path(@task_group)%>
</div>
<ul class="tasks_list">
<% @tasks.each do |task| %>
    <li class= "task_list">
      <h3><%= link_to task.name, task_group_task_path(@task_group,task) %></h3>
      Duration: <%= task.duration %> days |
      Status: <%= task.status %>
    </li>
<% end %>
</ul>

app/views/tasks/_form.html.erb
<% semantic_form_for ([@task_group, @task]) do |form| %>
  <% form.inputs do %>
     <%= form.input :name %>
     <%= form.input :duration %>
     <%= form.input :status, :as => :select,  :collection => TaskCategory.select('distinct name').map { |c| c.name } %>
     <% end %>
     <% form.buttons do %>
     <%= form.commit_button %>
     <% end %>
<% end %>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks Edit</h1>
<%= render "form" %>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>
<%= @tasks %>

app/views/tasks/new.html.erb
<h1>Create New Task</h1>
<%= render 'form' %>

app/views/tasks/release.html.erb
<h1> Show </h1>

app/views/tasks/show.html.erb
<h1><%= @task_group.name %></h1>
<h2>Task: <%= @task.name  %>

<div class="task_edit">
  <%= link_to "Edit", edit_task_path(@task) %></h2>
</div>
Duration: <%= @task.duration %> days <br />
Status: <%= @task.status %> <br />
Created At: <%= @task.created_at.to_s(:project_date) %>
<br />
<h3> Team Members: <%= render :partial => "task_groups/member_select" %> </h3>
<% @connected_people = connected_people(@connections) %>
<% @connected_people.each do |person| %>
  <%= link_to "#{person.name}", person_path(person) %> |
  <%= link_to "Release", person_task_release_path(person,@task) %>
  <br />
<% end %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>